initial commit
Oklukeok/Luke-s_Portfolio pull request #10
Opened 2022-09-15 18:39 UTC by Oklukeok

Add Modal "Pop -Up" to the work sections, when you click on the "see more" button

2022-09-15 18:55 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @Oklukeok 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media0.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

## Highlights:  
* All tests passed ✔️

## Required Changes:
- [ ] From now on, kindly make descriptive commit messages. `Initial commit` isn't descriptive of what you've done in this branch and it's wrong since this is not an initial commit 👍 
_Please check the comments below for more changes_

## Optional:
_Please check the comments below_
------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-15 18:55 UTC, ha-manel commented on index.html
>            <button type="button">See Project</button>
- [ ] Kindly fix the issue of the first card because it has 2 `see project` buttons.

![image](https://user-images.githubusercontent.com/50721479/190484828-1b7cf04f-8f7f-42ce-bc2c-fd26c6c0c11a.png)

2022-09-15 18:55 UTC, ha-manel commented on index.html
> +    <div class="project-modal" id ="project-modal">
- [ ] Great job with the design 👍 However we can't see the rest of the modal window (the text and the buttons).

![image](https://user-images.githubusercontent.com/50721479/190485000-9d714d99-867c-466f-a3ea-7a424c476235.png)

2022-09-15 18:55 UTC, ha-manel commented on index.html
> +                <div class="modal-grid">
- [ ] In the mobile version at certain widths the content of the modal window gets messed up. Kindly fix the issues 👍 

![image](https://user-images.githubusercontent.com/50721479/190485219-3b7da03e-ad68-4673-bf12-4c68443aeb04.png)

2022-09-15 18:55 UTC, ha-manel commented on popup.js
> +  document.getElementById('source-link').textContent = projects[0].source;
[OPTIONAL]
- [ ] Dynamic cards are working fine, but it would be better if you put the contents of the card in an object of the same format. Example: 

```
{
    name: "Submarine game",
    description: "A Phaser3 platform game built as part of the Microverse JavaScript program.",
    image: "link_to_image.jpg",
    technologies: ["Phaser3", "JavaScript", "Jest"],
    link: "link_to_live_version.com",
}
```
and then loop through the array of these objects and make a card with each iteration. This would make your code very clean, readable and easily maintainable 💯

2022-09-15 22:45 UTC, roshan-bajgain requested changes
Hi @Oklukeok, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

 ## Required Changes ♻️
- [ ] [Optional] An important requirement is missed by the previous reviewer, The projects section should be created dynamically with the information from the projects array. The already created HTML code for the projects list should be removed, and instead, it should be added via JavaScript. please remove the code from lines 90 to 212 and use it to render dynamically. eg:
`const projects = [
  {
    projectId: 'projectOne',
    name: 'Tonic',
    description: 'Lorem Ipsum is simply dummy text of the printing and '
    + 'typesetting industry. Lorem Ipsum has been the industry\'s '
    + 'standard dummy text ever since the 1500s, when an unknown printer '
    + 'took a galley of type and scrambled it to make a type specimen book. '
    + 'It has survived not only five centuries, but also the leap into electronic '
    + 'typesetting, remaining essent',
    featuredImage: 'assets/portfolio.png',
    technologies: ['html', 'css', 'javascript'],
    liveLink: 'your lilnk',
    sourceLink: 'your portfolio link',
  },`
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-15 22:45 UTC, roshan-bajgain commented on index.html
> +                <div class="modal-grid">
- [ ] As requested by the previous reviewer, please implement the changes as only the image is rendering in the pop-up window.
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/190519841-4edae91b-2764-4a17-a6ca-245939bf407f.png)
### Your design
![your design](https://user-images.githubusercontent.com/81727988/190519859-ef35e651-f108-46ad-938f-ecc27087657c.png)

2022-09-15 22:45 UTC, roshan-bajgain commented on index.html
> +                <div class="modal-grid">
- [ ] As requested by the previous reviewer, the see-live and see-source buttons are showing outside the page please fix it.
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/190520410-c237051a-4b84-4e00-b2eb-7efcbbe5e765.png)
### Your design
![your](https://user-images.githubusercontent.com/81727988/190520455-e7cf57d0-b395-43b1-a99c-547ffb1cc165.png)

2022-09-16 04:13 UTC, Oklukeok commented
Hello reviewer! I'd like to share with you some images of the changes that I've been working on.

2022-09-16 04:18 UTC, Oklukeok commented
Using the website in mobile deploy:
-View at the start of mobile display
![image](https://user-images.githubusercontent.com/93407216/190555559-7a02d409-18aa-44c8-87db-2ad6e9373d04.png)

-View at the limit of mobile display
![image](https://user-images.githubusercontent.com/93407216/190555706-8febe0f1-ce7c-455e-8f04-ad4ac88aad12.png)

2022-09-16 04:21 UTC, Oklukeok commented
Using the website in desktop deploy:
- At the start of desktop view:
![image](https://user-images.githubusercontent.com/93407216/190555952-cff36094-e91a-4fe3-97d5-e56cadf318fb.png)

-At the limit of desktop view:
![image](https://user-images.githubusercontent.com/93407216/190556082-8d5a8430-9d72-45d1-ace9-7c04956656fd.png)

2022-09-16 04:25 UTC, Oklukeok commented
I think the last reviewer helped me to improve my design! and I hope this submit already meets the requirements.

Thanks for taking the time for reading my words! Have a nice weekend!

2022-09-16 05:06 UTC, franclobo approved these changes
Hi @Oklukeok, 

# STATUS. APPROVED 😃 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors ✔️ 
- Correct GitHub flow ✔️ 
- Good comunication with code reviewer 💯 

## Optional suggestions
- **[OPTIONAL]** Please 🙏🏽 add the LICENSE file in your repocitory to have a professional README file.
- **[OPTIONAL]** Kindly use `overflow: scroll` in `#project-modal` to see all the popup window's elemnts 👇🏽 

https://user-images.githubusercontent.com/58642949/190560608-3484ac41-f78c-4346-a401-2719a8eba532.mp4

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 15:25 UTC, merged