Add Section Works and About me to HTML and CSS
Oklukeok/Luke-s_Portfolio pull request #2
Opened 2022-08-21 01:26 UTC by Oklukeok

Added new content to the web site: Works and About me.

2022-08-21 02:28 UTC, Reem-lab requested changes
# Hi @Oklukeok, 👋🏻👋🏻

Good job so far! 🔥🔥🚀🚀
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the functionality ✅
📌 Good commit messages ✅
📌Professional README file. ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-21 02:28 UTC, Reem-lab commented on index.html
> +          <p>CANOPY • Back End Dev • 2015 </p>
- [ ] Kindly update on `CANOPY` the font weight since I see it in you design different than the Figma template 👌🏻🚀
and update the color in it to match the figma design as much as possible ✅

2022-08-21 02:28 UTC, Reem-lab commented on index.html
> +        <div class="tonicTitle"><p>Tonic</p></div>
- [ ] Kindly use the tonic inside `hx` tag like `h2` or `h3` so you canmake your html page semantic and that is important for SEO reasons ✅🚀
- [ ] Kindly update the font weight to match the figma template as much as possible ✅👌🏻

- Your design
![image](https://user-images.githubusercontent.com/58553711/185772181-c24e3179-5c1b-4ba2-83dc-48b147de4b3a.png)

- Original design
![image](https://user-images.githubusercontent.com/58553711/185772189-79a82bae-68f6-48f2-b425-307cde7f3f9a.png)

2022-08-21 02:28 UTC, Reem-lab commented on index.html
> +          <p>A daily selection of privately personalized reads; no accounts or sign-ups required.</p>
- [ ] Kindly make the color here also the same as the figma template because I can see it different so please update it ✅🚀

2022-08-21 02:28 UTC, Reem-lab commented on index.html
> +        <button type="button">See Project</button>
- [ ] According to the requirements kindly Implement the button interactions (enable, hover, etc.). since I can't see the interactions in your project 🚀✅👌🏻

2022-08-21 02:28 UTC, Reem-lab commented on index.html
> +    </div>
- [ ] Great job so far but I think here the alignement for the elements is not right so kindly align them in the same line here so please align them to match the figma design as much as possible ✅✅👌🏻👌🏻👌🏻

- Your design
![image](https://user-images.githubusercontent.com/58553711/185772436-1edb0109-554c-4376-8736-61589a7eea01.png)

- Figma design
![image](https://user-images.githubusercontent.com/58553711/185772458-27ececce-33a5-46d1-bffa-9980f248714c.png)

2022-08-21 02:28 UTC, Reem-lab commented on index.html
> +      <div class="landingH3"><h3>LET’S CONNECT</h3></div>
- [ ] kindly decrease the font weight here since it is too big here not like the figma so kindly fix it 👌🏻

2022-08-21 02:28 UTC, Reem-lab commented on index.html
> +      </ul>
- [ ] Kindly add the missing parts here since I can't see the arrow in the side and I can't see the background color for the languages as well so please work on it to match the figma design as much as possible since it is one of the requirements ✅

- Your design
![image](https://user-images.githubusercontent.com/58553711/185772532-c907065c-b69b-4f2a-89ff-0597dc129158.png)

- Original design
![image](https://user-images.githubusercontent.com/58553711/185772545-f55153f0-bc6b-482a-b506-1abe9f1d26c3.png)

2022-08-21 02:28 UTC, Reem-lab commented on index.html
> +        <button type="button">Get my resume</button>
- [ ] According to the requirements kindly Implement the button interactions (enable, hover, etc.). since I can't see the interactions in your project 🚀✅👌🏻

2022-08-21 02:28 UTC, Reem-lab commented on index.html
> +            <img src="images/languajes/js.png" alt="">
- [ ] I think this path is broken since you didn't add the `languajes` directory to your project so i can't see the images displayed in the project so kindly add them 🚀👌🏻👌🏻

2022-08-21 02:28 UTC, Reem-lab commented on README.md
> +
- [ ] I think here you missed to add `get started` section so kindly add it and to more explanition you should add how any user can clone your repo and how to get in to the project and how to run it so you can add it as steps ✅👌🏻
That's very important for any user want to clone your repo that will help much

2022-08-21 08:14 UTC, emmiiorji requested changes
Hi @Oklukeok, 

# Status: Changes Required ♻️

Great work on making the changes requested by a previous reviewer 👏. I celebrate your tenacity.
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


![Almost there](https://user-images.githubusercontent.com/20554583/185782129-bf826f65-12b6-4d9f-8141-d8e8bab10d3c.gif)


 ## Highlights
- Implemented most of the requested changes
- Linter checks are passing
- Good commit messages


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-21 08:14 UTC, emmiiorji commented on index.html
> +    </div>
_[Optional]_ I suggest that you remove this section as it only tends to symbolize that the is display on a mobile device

2022-08-24 21:41 UTC, BertrandConxy requested changes
Hi @Oklukeok , 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 


## Highlights 💪 
- No linter errors
- correct flow is used
- good PR


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 21:41 UTC, BertrandConxy commented on index.html
> +          <div class="Q">
- [ ] Good job so far 👏.  The technology categories ("Languages", "Frameworks" and "Skills") are supposed to be in the list and each is in `li`. In addition, technology in each category ("Javascript", "HTML", "CSS") are also in list `ul` and each of them `li`. In other words, you are supposed to implement a nested list. in order to understand how to do it, please check out this [ article](https://www.webucator.com/article/how-to-properly-nest-lists-in-html/)
**HINT**
```
<ul>
  <li>Fruit
    <ul>
      <li>Bananas</li>
      <li>Apples
        <ul>
          <li>Green</li>
          <li>Red</li>
        </ul>
      </li>
      <li>Pears</li>
    </ul>
  </li>
  <li>Vegetables</li>
  <li>Meat</li>
</ul>
```

2022-08-25 22:52 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @Oklukeok, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 14:05 UTC, merged